apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: counter-app-pipeline
spec:
  tasks:

    - name: check-image-registry
      taskRef:
        name: check-image-registry

    - name: deploy-postgres
      runAfter:
        - check-image-registry
      taskRef:
        name: deploy-postgres

    - name: build-backend
      runAfter:
        - deploy-postgres
      taskRef:
        name: build-backend

    - name: deploy-backend
      runAfter:
        - build-backend
      taskRef:
        name: deploy-backend

    - name: build-nginx
      runAfter:
        - deploy-backend
      taskRef:
        name: build-nginx

    - name: deploy-nginx
      runAfter:
        - build-nginx
      taskRef:
        name: deploy-nginx

    - name: get-route
      runAfter:
        - deploy-nginx
      taskRef:
        name: get-route