apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: cnpg-ha-manual-backup
  namespace: counter-operator
spec:
  cluster:
    name: cnpg-ha
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io