apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: backend

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: backend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/khalidrizki/counter-docker-k8.git
      ref: operator-connected
    contextDir: backend

  strategy:
    type: Docker

  output:
    to:
      kind: ImageStreamTag
      name: backend:latest