apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nginx
spec:
  source:
    type: Git
    git:
      uri: https://github.com/khalidrizki/counter-docker-k8.git
      ref: main

  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: nginx/Dockerfile

  output:
    to:
      kind: ImageStreamTag
      name: nginx:latest

  triggers:
    - type: ConfigChange