apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-standby-pvc

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: ocs-storagecluster-ceph-rbd

  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-standby-script

data:
  start-standby.sh: |
    #!/bin/bash
    set -e

    if [ ! -f "$PGDATA/PG_VERSION" ]; then

      echo "Standby belum memiliki database."
      echo "Mengambil base backup dari Primary..."

      rm -rf "$PGDATA"/*

      export PGPASSWORD="$REPLICATION_PASSWORD"

      until pg_basebackup \
        -h postgres-primary \
        -p 5432 \
        -U "$REPLICATION_USER" \
        -D "$PGDATA" \
        -Fp \
        -Xs \
        -P \
        -R
      do
        echo "Primary belum siap. Coba lagi dalam 5 detik..."
        sleep 5
      done

    fi

    echo "Menjalankan PostgreSQL sebagai Standby..."

    exec postgres \
      -D "$PGDATA" \
      -c hot_standby=on
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-standby

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres-standby

  template:
    metadata:
      labels:
        app: postgres-standby

    spec:

      containers:
        - name: postgres

          image: postgres:16

          ports:
            - containerPort: 5432

          env:

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

            - name: REPLICATION_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: REPLICATION_USER

            - name: REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: REPLICATION_PASSWORD

          command:
            - /bin/bash
            - /scripts/start-standby.sh

          volumeMounts:

            - name: postgres-standby-storage
              mountPath: /var/lib/postgresql/data

            - name: standby-script
              mountPath: /scripts

      volumes:

        - name: postgres-standby-storage
          persistentVolumeClaim:
            claimName: postgres-standby-pvc

        - name: standby-script
          configMap:
            name: postgres-standby-script
            defaultMode: 0755