apiVersion: v1
kind: ConfigMap

metadata:
  name: postgres-primary-config

data:
  pg_hba.conf: |
    local   all             all                                     trust

    host    all             all             0.0.0.0/0               scram-sha-256

    host    replication     replicator      0.0.0.0/0               scram-sha-256
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  01-create-replication-user.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 \
      --username "$POSTGRES_USER" \
      --dbname "$POSTGRES_DB" <<-EOSQL

        CREATE ROLE ${REPLICATION_USER}
        WITH REPLICATION
        LOGIN
        PASSWORD '${REPLICATION_PASSWORD}';

    EOSQL
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-primary-rebuild
data:
  rebuild-standby.sh: |
    #!/bin/bash
    set -e

    if [ ! -f "$PGDATA/PG_VERSION" ]; then

      echo "=== Rebuild postgres-primary sebagai Standby ==="

      echo "Mengosongkan PGDATA..."
      rm -rf "$PGDATA"/*

      export PGPASSWORD="$REPLICATION_PASSWORD"

      echo "Mengambil base backup dari Primary baru..."

      until pg_basebackup \
        -h postgres-standby \
        -p 5432 \
        -U "$REPLICATION_USER" \
        -D "$PGDATA" \
        -Fp \
        -Xs \
        -P \
        -R
      do
        echo "Primary baru belum siap. Coba lagi dalam 5 detik..."
        sleep 5
      done

      echo "Base backup selesai."

    fi

    chmod 700 "$PGDATA"

    echo "Menjalankan PostgreSQL sebagai Standby..."

    exec postgres \
      -D "$PGDATA" \
      -c hot_standby=on
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-primary-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
spec:
  selector: 
    app: postgres-primary
  ports: 
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-primary

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres-primary

  template:
    metadata:
      labels:
        app: postgres-primary

    spec:
      containers:
        - name: postgres

          image: postgres:16

          ports:
            - containerPort: 5432

          command:
          - /bin/bash
          - /scripts/rebuild-standby.sh

          env:

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: REPLICATION_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: REPLICATION_USER

            - name: REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: REPLICATION_PASSWORD

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata


          volumeMounts:

            - name: postgres-primary-storage
              mountPath: /var/lib/postgresql/data

            - name: postgres-primary-config
              mountPath: /etc/postgresql

            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d

            - name: postgres-primary-rebuild
              mountPath: /scripts

      volumes:

        - name: postgres-primary-storage
          persistentVolumeClaim:
            #claimName: postgres-primary-pvc
            claimName: postgres-primary-rebuild-pvc

        - name: postgres-primary-config
          configMap:
            name: postgres-primary-config

        - name: postgres-init
          configMap:
            name: postgres-init
            defaultMode: 0755
        
        - name: postgres-primary-rebuild
          configMap:
            name: postgres-primary-rebuild
            defaultMode: 0755